django_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("polls.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("users.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

polls/urls.py
"""Polls app URL."""
from django.urls import path

from polls import views

app_name = "polls"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("question/add/", views.CreateQuestionView.as_view(), name="create-question"),
    path(
        "<int:pk>/choice/add/",
        views.CreateChoiceView.as_view(),
        name="create-choice",
    ),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.SubmitVote.as_view(), name="vote"),
]

users/urls.py
"""Accounts app URL Configuration."""
from django.urls import path
from django.views.generic import TemplateView

from users import views

app_name = "users"
urlpatterns = [
    path("", TemplateView.as_view(template_name="registration/signup.html"), name="signup"),
    path("signup/student/", views.StudentSignUpView.as_view(), name="student_signup"),
    path("signup/teacher/", views.TeacherSignUpView.as_view(), name="teacher_signup"),
]

polls/models.py
"""Polls models."""
from datetime import timedelta

from django.db import models
from django.utils.timezone import now


class Question(models.Model):
    """Question model class.

    Attributes:
    ----------
    question_text : string
        Holds the text for the question.
    pub_date : datetime
        Holds the date and time of the question.

    """

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self) -> str:
        """Return a string representation of Question."""
        return str(self.question_text)

    def was_published_recently(self):
        """Check if Question was published in last 24 hours.

        Returns:
        -------
        bool:
            True, if published in last 24 hours.
            False, otherwise.

        """
        return now() >= self.pub_date >= now() - timedelta(days=1)


class Choice(models.Model):
    """Choice model class.

    Attributes:
    ----------
    question : foreign key
        Holds a reference to the Question class object.
    choice_text : string
        Holds a string that represents a choice.

    """

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> str:
        """Return a string representation of Choice."""
        return str(self.choice_text)

users/models.py
"""Accounts models."""
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from users.managers import CustomUserManager


class CustomUser(AbstractUser):
    """Custom User class."""

    username = None
    email = models.EmailField(_("email address"), unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

    objects = CustomUserManager()

    def __str__(self):
        """Return email as the object's string representation."""
        return self.email

users/forms.py
"""Forms for accounts app."""
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from users.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """Registration form."""

    class Meta:
        """Meta class."""

        model = CustomUser
        fields = ("first_name", "last_name", "email", "password1", "password2")


class CustomUserChangeForm(UserChangeForm):
    """User profile change view."""

    class Meta:
        """Meta class."""

        model = CustomUser
        fields = ("email",)

polls/views.py
"""Polls app views."""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.utils.timezone import now
from django.views import View, generic

# Local imports
from polls.models import Choice, Question
from users.mixins import StudentRequiredMixin, TeacherRequiredMixin


class CreateQuestionView(TeacherRequiredMixin, generic.CreateView):
    """View to create question."""

    model = Question
    fields = ["question_text"]
    success_url = reverse_lazy("polls:index")

    def form_valid(self, form):
        """For valid form submission."""
        form.instance.pub_date = now()
        return super().form_valid(form)


class CreateChoiceView(TeacherRequiredMixin, generic.CreateView):
    """View to create choice."""

    model = Choice
    fields = ["choice_text"]

    def get_success_url(self):
        """Overwrite the `success_url`."""
        question_id = self.kwargs["pk"]
        return reverse_lazy("polls:detail", kwargs={"pk": question_id})

    def form_valid(self, form):
        """If the form data is valid, add current time as `pub_date`."""
        form.instance.question_id = self.kwargs["pk"]
        return super().form_valid(form)


class IndexView(generic.ListView):
    """Index view of polls app."""

    model = Question

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(LoginRequiredMixin, generic.DetailView):
    """Detail view of polls app."""

    model = Question


class ResultsView(LoginRequiredMixin, generic.DetailView):
    """Results view of polls app."""

    model = Question
    template_name = "polls/results.html"


class SubmitVote(StudentRequiredMixin, View):
    """Vote View."""

    def post(self, request, question_id):
        """Vote counter function."""
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST["choice"])
        except (KeyError, Choice.DoesNotExist):
            return render(
                request,
                "polls/details.html",
                {
                    "question": question,
                    "error_message": "You didn't select a choice.",
                },
            )
        else:
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

users/views.py
"""Accounts view."""
from django.urls import reverse_lazy
from django.views import generic

from users.forms import CustomUserCreationForm
from users.models import CustomUser


class StudentSignUpView(generic.CreateView):
    """Sign up view for Student Users."""

    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = "generic_create_update_form.html"
    success_url = reverse_lazy("login")
    extra_context = {"title_text": "Student Sign Up", "button_text": "Register"}

    def form_valid(self, form: object) -> object:
        """For valid form submission."""
        form.instance.is_student = True
        return super().form_valid(form)


class TeacherSignUpView(generic.CreateView):
    """Sign up view for Teacher Users."""

    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = "generic_create_update_form.html"
    success_url = reverse_lazy("login")
    extra_context = {"title_text": "Teacher Sign Up", "button_text": "Register"}

    def form_valid(self, form: object) -> object:
        """For valid form submission."""
        form.instance.is_teacher = True
        return super().form_valid(form)

polls/templates/polls/choice_form.html
{% extends "base_generic.html" %}
{% load django_bootstrap5 %}
{% block title %}
    Add a choice for
{% endblock title %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary justify-center">
                        <i class="fa-solid fa-floppy-disk"></i> Save
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

polls/templates/polls/question_detail.html
{% extends "base_generic.html" %}
{% block title %}
    Question: {{ question.question_text }}
{% endblock title %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if error_message %}<div class="alert alert-danger" role="alert">{{ error_message }}</div>{% endif %}
            <form action="{% url 'polls:vote' question.id %}" method="post">
                {% csrf_token %}
                {% for choice in question.choice_set.all %}
                    <div class="row">
                        <div class="col-md-1">
                            <input type="radio"
                                   name="choice"
                                   id="choice{{ forloop.counter }}"
                                   value="{{ choice.id }}"/>
                        </div>
                        <div class="col-md-5 mb-1">
                            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                        </div>
                    </div>
                {% endfor %}
                <div class="text-center mb-4">
                    {% if user.is_authenticated and user.is_student %}
                        <input class="btn btn-success" type="submit" value="Vote" />
                    {% else %}
                        <input class="btn btn-success" type="submit" value="Vote" disabled />
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
    <div class="row justify-content-center mb-4">
        <div class="col-md-4">
            <div class="text-center">
                {% if user.is_authenticated and user.is_teacher %}
                    <a class="btn btn-warning"
                       href="{% url 'polls:create-choice' question.id %}">
                        <i class="fa-solid fa-plus"></i> Add choice
                    </a>
                    <a class="btn btn-warning" href="{% url 'polls:results' question.id %}">
                        <i class="fa-solid fa-poll"></i> View Polling Result
                    </a>
                {% endif %}
                {% if user.is_authenticated and user.is_student %}
                    <a class="btn btn-warning disabled"
                       href="{% url 'polls:create-choice' question.id %}"
                       role="button"
                       aria-disabled="true">
                        <i class="fa-solid fa-plus"></i> Add choice
                    </a>
                    <a class="btn btn-warning disabled"
                       href="{% url 'polls:results' question.id %}"
                       role="button"
                       aria-disabled="true">
                        <i class="fa-solid fa-poll"></i> View Polling Result
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

polls/templates/polls/question_form.html
{% extends "base_generic.html" %}
{% load django_bootstrap5 %}
{% block title %}
    Add a new question
{% endblock title %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary justify-center">
                        <i class="fa-solid fa-floppy-disk"></i> Save
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

polls/templates/polls/question_list.html
{% extends "base_generic.html" %}
{% block title %}
    Available Polls
{% endblock title %}
{% block content %}
    <div class="row justify-content-center mb-4">
        <div class="col-md-6">
            {% if object_list %}
                <ol>
                    {% for question in object_list %}
                        <li>
                            <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                        </li>
                    {% endfor %}
                </ol>
            {% else %}
                <p>No polls are available.</p>
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="text-center">
                {% if user.is_authenticated and user.is_teacher %}
                    <a class="btn btn-warning" href="{% url 'polls:create-question' %}">
                        <i class="fa-solid fa-plus"></i> Create Question
                    </a>
                {% endif %}
                {% if user.is_authenticated and user.is_student %}
                    <a class="btn btn-warning disabled"
                       href="{% url 'polls:create-question' %}"
                       role="button"
                       aria-disabled="true">
                        <i class="fa-solid fa-plus"></i> Create Question
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

polls/templates/polls/results.html
{% extends "base_generic.html" %}
{% block title %}
    {{ question.question_text }}
{% endblock title %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="d-flex justify-content-center">
            <div class="col-md-6">
                <ul>
                    {% for choice in question.choice_set.all %}
                        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
                    {% endfor %}
                </ul>
                <br/>
                <div class="row">
                    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}

users/templates/base_generic.html
{# Load the tag library #}
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="us-en">
    <head>
        <meta charset="UTF-8" />
        <meta name="description" content="Polls App" />
        <meta name="keywords" content="HTML, CSS, JavaScript" />
        <meta name="author" content="John Doe" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="shortcut icon"
              type="image/png"
              href="{% static 'img/favicon.ico' %}"/>
        <title>Polls App</title>
        {# Load CSS and JavaScript #}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
        <link href="{% static 'fontawesomefree/css/all.min.css' %}"
              rel="stylesheet"
              type="text/css"/>
        {% block style %}
        {% endblock style %}
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="container">
            <h1 class="text-center fw-bold mb-5">
                {% block title %}
                {% endblock title %}
            </h1>
            {% block content %}
            {% endblock content %}
        </div>
        {% include "footer.html" %}
    </body>
</html>

users/templates/footer.html
<footer class="footer pt-3 mt-4 text-muted">
    <div class="container">
        Django Project template is powered by
        <a target="_blank" href="https://getbootstrap.com/">Bootstrap</a>
        and
        <a target="_blank" href="https://fontawesome.com/">Font awesome</a>.
    </div>
</footer>

users/templates/generic_create_update_form.html
{% extends "base_generic.html" %}
{% load django_bootstrap5 %}
{% block title %}
    {{ title_text }}
{% endblock title %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div class="col-md-4">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {{ form.media }}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">{{ button_text }}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

users/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark justify-content-between">
    <div class="container">
        <a class="navbar-brand" href="{% url 'polls:index' %}">
            <i class="fa-solid fa-square-poll-vertical"></i> Polls App
        </a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarsExampleDefault"
                aria-controls="navbarsExampleDefault"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="#navbarsExampleDefault">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <div class="dropdown">
                        <a class="nav-link dropdown-toggle"
                           role="button"
                           data-toggle="dropdown"
                           data-bs-toggle="dropdown"
                           aria-expanded="false">
                            <i class="fa-solid fa-user-shield"></i> {{ user.email }}
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item" href="{% url 'password_change' %}">
                                    <i class="fa-solid fa-user-cog"></i> Change password
                                </a>
                            </li>
                            <li>
                                <div class="dropdown-divider"></div>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'logout' %}">
                                    <i class="fa-solid fa-sign-out-alt"></i> Log out
                                </a>
                            </li>
                        </ul>
                    </div>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">
                            <i class="fa-solid fa-sign-in"></i> Sign in
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:signup' %}">
                            <i class="fa-solid fa-user-edit"></i> Sign up
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>